# Generated by Django 5.2.7 on 2025-10-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=250)),
                ('disc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='documents/')),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'Junly'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'Octover'), ('Nov', 'November'), ('Dec', 'December')], default='Oct', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=100)),
                ('net_salary', models.CharField(max_length=50)),
                ('pf', models.CharField(max_length=50)),
                ('uan_no', models.CharField(max_length=50)),
                ('date_of_joining', models.CharField(max_length=50)),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'Junly'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'Octover'), ('Nov', 'November'), ('Dec', 'December')], default='Oct', max_length=3)),
                ('file', models.FileField(upload_to='salary_sleep/')),
            ],
        ),
    ]
