# Generated by Django 5.2.7 on 2025-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Info',
        ),
        migrations.AlterField(
            model_name='salarysleep',
            name='file',
            field=models.FileField(upload_to='salary_slips/'),
        ),
    ]
