# Generated by Django 5.2.6 on 2025-11-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0002_delete_add_info_alter_salarysleep_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'Junly'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'Octover'), ('Nov', 'November'), ('Dec', 'December')], default='Nov', max_length=3),
        ),
        migrations.AlterField(
            model_name='salarysleep',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'Junly'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'Octover'), ('Nov', 'November'), ('Dec', 'December')], default='Nov', max_length=3),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
